version: '2.2'
services:
  zephyr-development:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    restart: always
    cpus: '4'
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - /home/user/zephyr/development:/workdir
    restart: always
    privileged: true