version: '2.2'
services:
  zephyr-development:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    restart: always
    cpus: '4'
    privileged: true
    volumes:
      - ./workdir:/workdir
    restart: always